// <auto-generated />
using Assignment1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Assignment1.Data.Migrations
{
    [DbContext(typeof(AssignmentDbContext))]
    partial class AssignmentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Assignment1.Models.Assignments", b =>
                {
                    b.Property<int>("Assignmentid")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Assignmenttopic");

                    b.Property<string>("CourseAssignmentsAssignment_Name");

                    b.Property<string>("Submmittedto");

                    b.HasKey("Assignmentid");

                    b.HasIndex("CourseAssignmentsAssignment_Name");

                    b.ToTable("Asignmentss");
                });

            modelBuilder.Entity("Assignment1.Models.AuthenticationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password");

                    b.Property<string>("Token");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("AuthUsers");
                });

            modelBuilder.Entity("Assignment1.Models.CourseAssignments", b =>
                {
                    b.Property<string>("Assignment_Name")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Assignment_Name");

                    b.ToTable("CourseAsignmentss");
                });

            modelBuilder.Entity("Assignment1.Models.Courses", b =>
                {
                    b.Property<string>("CourseId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CourseAssignmentsAssignment_Name");

                    b.Property<string>("CourseName");

                    b.Property<string>("Semester");

                    b.Property<string>("UserCoursesFull_Name");

                    b.HasKey("CourseId");

                    b.HasIndex("CourseAssignmentsAssignment_Name");

                    b.HasIndex("UserCoursesFull_Name");

                    b.ToTable("Coursess");
                });

            modelBuilder.Entity("Assignment1.Models.UserCourses", b =>
                {
                    b.Property<string>("Full_Name")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Full_Name");

                    b.ToTable("Usercourses");
                });

            modelBuilder.Entity("Assignment1.Models.Assignments", b =>
                {
                    b.HasOne("Assignment1.Models.CourseAssignments")
                        .WithMany("Assignmentss")
                        .HasForeignKey("CourseAssignmentsAssignment_Name");
                });

            modelBuilder.Entity("Assignment1.Models.Courses", b =>
                {
                    b.HasOne("Assignment1.Models.CourseAssignments")
                        .WithMany("Coursess")
                        .HasForeignKey("CourseAssignmentsAssignment_Name");

                    b.HasOne("Assignment1.Models.UserCourses")
                        .WithMany("Coursess")
                        .HasForeignKey("UserCoursesFull_Name");
                });
#pragma warning restore 612, 618
        }
    }
}
